# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include("${CURRENT_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake")

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/boost_install
    REF boost-1.72.0
    SHA512 0c3b319d0828df2dfafd60c02c8d0b4a349c0843162f02735954a2e586e846ce76b1ccca0c7d05669486f0f37bd0740fee66c8f74461ef6ff397cb0832dff886
    HEAD_REF master
)

boost_modular_build(SOURCE_PATH ${SOURCE_PATH})

# BOOST_ROOT = $(.boost-build-file:D) ;
# BOOST_BUILD = [ MATCH --boost-build=(.*) : $(ARGV) ] ;
# BOOST_BUILD ?= tools/build/src ;
# boost-build $(BOOST_BUILD) ;